version: '3.9'

services:
  # https://etcd.io/docs/v3.5/op-guide/container/
  etcd1:
    container_name: etcd1
    image: gcr.io/etcd-development/etcd
    ports:
      - 2379:2379
      - 2380:2380
    volumes:
      - ./data/etcd:/etcd-data
    command: ["sh", "-c", "/usr/local/bin/etcd --data-dir=/etcd-data --name etcd1 --initial-advertise-peer-urls http://etcd1:2380 --listen-peer-urls http://0.0.0.0:2380 --advertise-client-urls http://etcd1:2379 --listen-client-urls http://0.0.0.0:2379 --initial-cluster etcd1=http://etcd1:2380"]

    